name: Report a Problem
description: File a bug report
title: "[Issue]: "
labels: ["Entomology"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description
      description: Please describe the issue in your own words
      placeholder: This is how you would see the problem again
    validations:
      required: true
  - type: textarea
    id: logcat
    attributes:
      label: Logcat Output
      description: Long press inside this box and select "Paste"
      placeholder: This is a logcat, not a secondary description
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: requirements
    attributes:
      label: Usage Requirements
      description: |
          amiibo binary key file(s). (Encryption keys cannot be shared for legal reasons)
          Blank NTAG215 tags, Power Tags, Amiiqo / N2 Elite, or Flask (Sold separately)
          amiibo backups or amiibo. (Backups cannot be shared for legal reasons)

          Writing an NFC tag is effectively permanent. Overwriting breaks recognition.
              Cards, coins, or stickers cannot be used as rewriteable emulator devices.
          Only NTAG215 is recognized as an amiibo. No other NFC specifications work.
          Only Android devices with 4.1+ and NFC / Bluetooth hardware are supported.

          By submitting this issue, you confirm reading the usage requirements for TagMo
      options:
        - label: I have read and understood the usage requirements for TagMo
          required: true
