name: Logcat Email Log
description: TagMo Use ONLY
title: "[Email]:  PST"
labels: ["Entomology"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description
      description: The body content of the email
      placeholder:
    validations:
      required: true
  - type: textarea
    id: logcat
    attributes:
      label: Logcat Output
      description: The log attached to the email
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: authorization
    attributes:
      label: Use Authorizations
      options:
        - label: I am authorized to submit this issue by TagMo collaborators
          required: true
