name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["logcat"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description
      description: Please describe the issue in your own words
      placeholder: Issues without a meaningful description are closed
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logcat Output
      description: Long press inside this box and select "Paste"
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Usage Requirements
      description: |
          amiibo™ binary key file(s). (Encryption keys cannot be shared for legal reasons)
          Blank NTAG215 tags, Power Tags, Amiiqo / N2 Elite, or Flask (Sold separately)
          amiibo™ backups or amiibo™. (Backups cannot be shared for legal reasons)

          Writing an NFC tag is effectively permanent. Overwriting breaks amiibo™ recognition.
              Cards, coins, or stickers cannot replace rewriteable amiibo™ emulator devices.
          Only NTAG215 is recognized as an amiibo™. No other NFC tag formats are supported.
          Only Android phones with Android 4.1+ and NFC / Bluetooth hardware are supported.

          By submitting this issue, you confirm reading the usage requirements for TagMo
      options:
        - label: I have read and understood the usage requirements for TagMo
          required: true
