name: Logcat Email
description: TagMo Use ONLY
title: "[Email]:  PST"
labels: ["logcat"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description
      description: The body content of the email
      placeholder:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logcat Output
      description: The log attached to the email
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Use Authorization
      options:
        - label: I am authorized to submit this issue by TagMo collaborators
          required: true
